// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jpPoolProto.proto

package com.ifeng.recom.mixrecall.common.model;

public final class JpPoolProbuf {
  private JpPoolProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JpPoolDocumentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string readableFeatures = 1;
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    boolean hasReadableFeatures();
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    String getReadableFeatures();
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    com.google.protobuf.ByteString
        getReadableFeaturesBytes();

    // optional string simId = 2;
    /**
     * <code>optional string simId = 2;</code>
     */
    boolean hasSimId();
    /**
     * <code>optional string simId = 2;</code>
     */
    String getSimId();
    /**
     * <code>optional string simId = 2;</code>
     */
    com.google.protobuf.ByteString
        getSimIdBytes();

    // optional string docid = 3;
    /**
     * <code>optional string docid = 3;</code>
     */
    boolean hasDocid();
    /**
     * <code>optional string docid = 3;</code>
     */
    String getDocid();
    /**
     * <code>optional string docid = 3;</code>
     */
    com.google.protobuf.ByteString
        getDocidBytes();

    // optional string date = 4;
    /**
     * <code>optional string date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>optional string date = 4;</code>
     */
    String getDate();
    /**
     * <code>optional string date = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // optional string title = 5;
    /**
     * <code>optional string title = 5;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 5;</code>
     */
    String getTitle();
    /**
     * <code>optional string title = 5;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string hotBoost = 6;
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    boolean hasHotBoost();
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    String getHotBoost();
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    com.google.protobuf.ByteString
        getHotBoostBytes();

    // optional bool hasThumnail = 7;
    /**
     * <code>optional bool hasThumnail = 7;</code>
     */
    boolean hasHasThumnail();
    /**
     * <code>optional bool hasThumnail = 7;</code>
     */
    boolean getHasThumnail();

    // optional string docType = 8;
    /**
     * <code>optional string docType = 8;</code>
     */
    boolean hasDocType();
    /**
     * <code>optional string docType = 8;</code>
     */
    String getDocType();
    /**
     * <code>optional string docType = 8;</code>
     */
    com.google.protobuf.ByteString
        getDocTypeBytes();

    // optional string source = 9;
    /**
     * <code>optional string source = 9;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 9;</code>
     */
    String getSource();
    /**
     * <code>optional string source = 9;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    // optional string cotag = 10;
    /**
     * <code>optional string cotag = 10;</code>
     */
    boolean hasCotag();
    /**
     * <code>optional string cotag = 10;</code>
     */
    String getCotag();
    /**
     * <code>optional string cotag = 10;</code>
     */
    com.google.protobuf.ByteString
        getCotagBytes();

    // optional bool isJp = 11;
    /**
     * <code>optional bool isJp = 11;</code>
     */
    boolean hasIsJp();
    /**
     * <code>optional bool isJp = 11;</code>
     */
    boolean getIsJp();

    // optional string why = 12;
    /**
     * <code>optional string why = 12;</code>
     */
    boolean hasWhy();
    /**
     * <code>optional string why = 12;</code>
     */
    String getWhy();
    /**
     * <code>optional string why = 12;</code>
     */
    com.google.protobuf.ByteString
        getWhyBytes();
  }
  /**
   * Protobuf type {@code JpPoolDocument}
   */
  public static final class JpPoolDocument extends
      com.google.protobuf.GeneratedMessage
      implements JpPoolDocumentOrBuilder {
    // Use JpPoolDocument.newBuilder() to construct.
    private JpPoolDocument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JpPoolDocument(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JpPoolDocument defaultInstance;
    public static JpPoolDocument getDefaultInstance() {
      return defaultInstance;
    }

    public JpPoolDocument getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JpPoolDocument(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              readableFeatures_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              simId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              docid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              date_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              title_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              hotBoost_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              hasThumnail_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              docType_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              source_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              cotag_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              isJp_ = input.readBool();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              why_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JpPoolProbuf.internal_static_JpPoolDocument_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JpPoolProbuf.internal_static_JpPoolDocument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JpPoolDocument.class, Builder.class);
    }

    public static com.google.protobuf.Parser<JpPoolDocument> PARSER =
        new com.google.protobuf.AbstractParser<JpPoolDocument>() {
      public JpPoolDocument parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JpPoolDocument(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<JpPoolDocument> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string readableFeatures = 1;
    public static final int READABLEFEATURES_FIELD_NUMBER = 1;
    private Object readableFeatures_;
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    public boolean hasReadableFeatures() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    public String getReadableFeatures() {
      Object ref = readableFeatures_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          readableFeatures_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string readableFeatures = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReadableFeaturesBytes() {
      Object ref = readableFeatures_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        readableFeatures_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string simId = 2;
    public static final int SIMID_FIELD_NUMBER = 2;
    private Object simId_;
    /**
     * <code>optional string simId = 2;</code>
     */
    public boolean hasSimId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string simId = 2;</code>
     */
    public String getSimId() {
      Object ref = simId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          simId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string simId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSimIdBytes() {
      Object ref = simId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        simId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string docid = 3;
    public static final int DOCID_FIELD_NUMBER = 3;
    private Object docid_;
    /**
     * <code>optional string docid = 3;</code>
     */
    public boolean hasDocid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string docid = 3;</code>
     */
    public String getDocid() {
      Object ref = docid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          docid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string docid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDocidBytes() {
      Object ref = docid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        docid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private Object date_;
    /**
     * <code>optional string date = 4;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string date = 4;</code>
     */
    public String getDate() {
      Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string title = 5;
    public static final int TITLE_FIELD_NUMBER = 5;
    private Object title_;
    /**
     * <code>optional string title = 5;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string hotBoost = 6;
    public static final int HOTBOOST_FIELD_NUMBER = 6;
    private Object hotBoost_;
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    public boolean hasHotBoost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    public String getHotBoost() {
      Object ref = hotBoost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hotBoost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hotBoost = 6;</code>
     */
    public com.google.protobuf.ByteString
        getHotBoostBytes() {
      Object ref = hotBoost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hotBoost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool hasThumnail = 7;
    public static final int HASTHUMNAIL_FIELD_NUMBER = 7;
    private boolean hasThumnail_;
    /**
     * <code>optional bool hasThumnail = 7;</code>
     */
    public boolean hasHasThumnail() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool hasThumnail = 7;</code>
     */
    public boolean getHasThumnail() {
      return hasThumnail_;
    }

    // optional string docType = 8;
    public static final int DOCTYPE_FIELD_NUMBER = 8;
    private Object docType_;
    /**
     * <code>optional string docType = 8;</code>
     */
    public boolean hasDocType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string docType = 8;</code>
     */
    public String getDocType() {
      Object ref = docType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          docType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string docType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDocTypeBytes() {
      Object ref = docType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        docType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string source = 9;
    public static final int SOURCE_FIELD_NUMBER = 9;
    private Object source_;
    /**
     * <code>optional string source = 9;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string source = 9;</code>
     */
    public String getSource() {
      Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string cotag = 10;
    public static final int COTAG_FIELD_NUMBER = 10;
    private Object cotag_;
    /**
     * <code>optional string cotag = 10;</code>
     */
    public boolean hasCotag() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string cotag = 10;</code>
     */
    public String getCotag() {
      Object ref = cotag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cotag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cotag = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCotagBytes() {
      Object ref = cotag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cotag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool isJp = 11;
    public static final int ISJP_FIELD_NUMBER = 11;
    private boolean isJp_;
    /**
     * <code>optional bool isJp = 11;</code>
     */
    public boolean hasIsJp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional bool isJp = 11;</code>
     */
    public boolean getIsJp() {
      return isJp_;
    }

    // optional string why = 12;
    public static final int WHY_FIELD_NUMBER = 12;
    private Object why_;
    /**
     * <code>optional string why = 12;</code>
     */
    public boolean hasWhy() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string why = 12;</code>
     */
    public String getWhy() {
      Object ref = why_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          why_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string why = 12;</code>
     */
    public com.google.protobuf.ByteString
        getWhyBytes() {
      Object ref = why_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        why_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      readableFeatures_ = "";
      simId_ = "";
      docid_ = "";
      date_ = "";
      title_ = "";
      hotBoost_ = "";
      hasThumnail_ = false;
      docType_ = "";
      source_ = "";
      cotag_ = "";
      isJp_ = false;
      why_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReadableFeaturesBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSimIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDocidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTitleBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getHotBoostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, hasThumnail_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDocTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getCotagBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBool(11, isJp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getWhyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReadableFeaturesBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSimIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDocidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTitleBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getHotBoostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, hasThumnail_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDocTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSourceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCotagBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isJp_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getWhyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JpPoolDocument parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JpPoolDocument parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JpPoolDocument parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JpPoolDocument parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JpPoolDocument parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JpPoolDocument parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JpPoolDocument parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JpPoolDocument parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JpPoolDocument parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JpPoolDocument parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JpPoolDocument prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JpPoolDocument}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JpPoolDocumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JpPoolProbuf.internal_static_JpPoolDocument_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JpPoolProbuf.internal_static_JpPoolDocument_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JpPoolDocument.class, Builder.class);
      }

      // Construct using com.ifeng.recom.mixrecall.common.model.JpPoolProbuf.JpPoolDocument.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        readableFeatures_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        simId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        docid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        hotBoost_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        hasThumnail_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        docType_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        cotag_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        isJp_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        why_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JpPoolProbuf.internal_static_JpPoolDocument_descriptor;
      }

      public JpPoolDocument getDefaultInstanceForType() {
        return JpPoolDocument.getDefaultInstance();
      }

      public JpPoolDocument build() {
        JpPoolDocument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JpPoolDocument buildPartial() {
        JpPoolDocument result = new JpPoolDocument(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.readableFeatures_ = readableFeatures_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.simId_ = simId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.docid_ = docid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hotBoost_ = hotBoost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.hasThumnail_ = hasThumnail_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.docType_ = docType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cotag_ = cotag_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.isJp_ = isJp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.why_ = why_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JpPoolDocument) {
          return mergeFrom((JpPoolDocument)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JpPoolDocument other) {
        if (other == JpPoolDocument.getDefaultInstance()) return this;
        if (other.hasReadableFeatures()) {
          bitField0_ |= 0x00000001;
          readableFeatures_ = other.readableFeatures_;
          onChanged();
        }
        if (other.hasSimId()) {
          bitField0_ |= 0x00000002;
          simId_ = other.simId_;
          onChanged();
        }
        if (other.hasDocid()) {
          bitField0_ |= 0x00000004;
          docid_ = other.docid_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000008;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000010;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasHotBoost()) {
          bitField0_ |= 0x00000020;
          hotBoost_ = other.hotBoost_;
          onChanged();
        }
        if (other.hasHasThumnail()) {
          setHasThumnail(other.getHasThumnail());
        }
        if (other.hasDocType()) {
          bitField0_ |= 0x00000080;
          docType_ = other.docType_;
          onChanged();
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000100;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasCotag()) {
          bitField0_ |= 0x00000200;
          cotag_ = other.cotag_;
          onChanged();
        }
        if (other.hasIsJp()) {
          setIsJp(other.getIsJp());
        }
        if (other.hasWhy()) {
          bitField0_ |= 0x00000800;
          why_ = other.why_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JpPoolDocument parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JpPoolDocument) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string readableFeatures = 1;
      private Object readableFeatures_ = "";
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public boolean hasReadableFeatures() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public String getReadableFeatures() {
        Object ref = readableFeatures_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          readableFeatures_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReadableFeaturesBytes() {
        Object ref = readableFeatures_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          readableFeatures_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public Builder setReadableFeatures(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        readableFeatures_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public Builder clearReadableFeatures() {
        bitField0_ = (bitField0_ & ~0x00000001);
        readableFeatures_ = getDefaultInstance().getReadableFeatures();
        onChanged();
        return this;
      }
      /**
       * <code>optional string readableFeatures = 1;</code>
       */
      public Builder setReadableFeaturesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        readableFeatures_ = value;
        onChanged();
        return this;
      }

      // optional string simId = 2;
      private Object simId_ = "";
      /**
       * <code>optional string simId = 2;</code>
       */
      public boolean hasSimId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string simId = 2;</code>
       */
      public String getSimId() {
        Object ref = simId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          simId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string simId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSimIdBytes() {
        Object ref = simId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          simId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string simId = 2;</code>
       */
      public Builder setSimId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        simId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string simId = 2;</code>
       */
      public Builder clearSimId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        simId_ = getDefaultInstance().getSimId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string simId = 2;</code>
       */
      public Builder setSimIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        simId_ = value;
        onChanged();
        return this;
      }

      // optional string docid = 3;
      private Object docid_ = "";
      /**
       * <code>optional string docid = 3;</code>
       */
      public boolean hasDocid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string docid = 3;</code>
       */
      public String getDocid() {
        Object ref = docid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          docid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string docid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDocidBytes() {
        Object ref = docid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          docid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string docid = 3;</code>
       */
      public Builder setDocid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        docid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string docid = 3;</code>
       */
      public Builder clearDocid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        docid_ = getDefaultInstance().getDocid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string docid = 3;</code>
       */
      public Builder setDocidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        docid_ = value;
        onChanged();
        return this;
      }

      // optional string date = 4;
      private Object date_ = "";
      /**
       * <code>optional string date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public String getDate() {
        Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder setDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }

      // optional string title = 5;
      private Object title_ = "";
      /**
       * <code>optional string title = 5;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string title = 5;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string title = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 5;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 5;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 5;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        title_ = value;
        onChanged();
        return this;
      }

      // optional string hotBoost = 6;
      private Object hotBoost_ = "";
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public boolean hasHotBoost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public String getHotBoost() {
        Object ref = hotBoost_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hotBoost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public com.google.protobuf.ByteString
          getHotBoostBytes() {
        Object ref = hotBoost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hotBoost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public Builder setHotBoost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hotBoost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public Builder clearHotBoost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hotBoost_ = getDefaultInstance().getHotBoost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hotBoost = 6;</code>
       */
      public Builder setHotBoostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        hotBoost_ = value;
        onChanged();
        return this;
      }

      // optional bool hasThumnail = 7;
      private boolean hasThumnail_ ;
      /**
       * <code>optional bool hasThumnail = 7;</code>
       */
      public boolean hasHasThumnail() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool hasThumnail = 7;</code>
       */
      public boolean getHasThumnail() {
        return hasThumnail_;
      }
      /**
       * <code>optional bool hasThumnail = 7;</code>
       */
      public Builder setHasThumnail(boolean value) {
        bitField0_ |= 0x00000040;
        hasThumnail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hasThumnail = 7;</code>
       */
      public Builder clearHasThumnail() {
        bitField0_ = (bitField0_ & ~0x00000040);
        hasThumnail_ = false;
        onChanged();
        return this;
      }

      // optional string docType = 8;
      private Object docType_ = "";
      /**
       * <code>optional string docType = 8;</code>
       */
      public boolean hasDocType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string docType = 8;</code>
       */
      public String getDocType() {
        Object ref = docType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          docType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string docType = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDocTypeBytes() {
        Object ref = docType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          docType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string docType = 8;</code>
       */
      public Builder setDocType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        docType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string docType = 8;</code>
       */
      public Builder clearDocType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        docType_ = getDefaultInstance().getDocType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string docType = 8;</code>
       */
      public Builder setDocTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        docType_ = value;
        onChanged();
        return this;
      }

      // optional string source = 9;
      private Object source_ = "";
      /**
       * <code>optional string source = 9;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public String getSource() {
        Object ref = source_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder setSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000100);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 9;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        source_ = value;
        onChanged();
        return this;
      }

      // optional string cotag = 10;
      private Object cotag_ = "";
      /**
       * <code>optional string cotag = 10;</code>
       */
      public boolean hasCotag() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string cotag = 10;</code>
       */
      public String getCotag() {
        Object ref = cotag_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cotag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string cotag = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCotagBytes() {
        Object ref = cotag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cotag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cotag = 10;</code>
       */
      public Builder setCotag(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cotag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cotag = 10;</code>
       */
      public Builder clearCotag() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cotag_ = getDefaultInstance().getCotag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cotag = 10;</code>
       */
      public Builder setCotagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        cotag_ = value;
        onChanged();
        return this;
      }

      // optional bool isJp = 11;
      private boolean isJp_ ;
      /**
       * <code>optional bool isJp = 11;</code>
       */
      public boolean hasIsJp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bool isJp = 11;</code>
       */
      public boolean getIsJp() {
        return isJp_;
      }
      /**
       * <code>optional bool isJp = 11;</code>
       */
      public Builder setIsJp(boolean value) {
        bitField0_ |= 0x00000400;
        isJp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isJp = 11;</code>
       */
      public Builder clearIsJp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        isJp_ = false;
        onChanged();
        return this;
      }

      // optional string why = 12;
      private Object why_ = "";
      /**
       * <code>optional string why = 12;</code>
       */
      public boolean hasWhy() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string why = 12;</code>
       */
      public String getWhy() {
        Object ref = why_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          why_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string why = 12;</code>
       */
      public com.google.protobuf.ByteString
          getWhyBytes() {
        Object ref = why_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          why_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string why = 12;</code>
       */
      public Builder setWhy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        why_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string why = 12;</code>
       */
      public Builder clearWhy() {
        bitField0_ = (bitField0_ & ~0x00000800);
        why_ = getDefaultInstance().getWhy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string why = 12;</code>
       */
      public Builder setWhyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        why_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:JpPoolDocument)
    }

    static {
      defaultInstance = new JpPoolDocument(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JpPoolDocument)
  }

  public interface JpPoolProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .JpPoolDocument document = 1;
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    java.util.List<JpPoolDocument>
        getDocumentList();
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    JpPoolDocument getDocument(int index);
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    int getDocumentCount();
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    java.util.List<? extends JpPoolDocumentOrBuilder>
        getDocumentOrBuilderList();
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    JpPoolDocumentOrBuilder getDocumentOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code JpPoolProto}
   */
  public static final class JpPoolProto extends
      com.google.protobuf.GeneratedMessage
      implements JpPoolProtoOrBuilder {
    // Use JpPoolProto.newBuilder() to construct.
    private JpPoolProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JpPoolProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JpPoolProto defaultInstance;
    public static JpPoolProto getDefaultInstance() {
      return defaultInstance;
    }

    public JpPoolProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JpPoolProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                document_ = new java.util.ArrayList<JpPoolDocument>();
                mutable_bitField0_ |= 0x00000001;
              }
              document_.add(input.readMessage(JpPoolDocument.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          document_ = java.util.Collections.unmodifiableList(document_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JpPoolProbuf.internal_static_JpPoolProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JpPoolProbuf.internal_static_JpPoolProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JpPoolProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<JpPoolProto> PARSER =
        new com.google.protobuf.AbstractParser<JpPoolProto>() {
      public JpPoolProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JpPoolProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<JpPoolProto> getParserForType() {
      return PARSER;
    }

    // repeated .JpPoolDocument document = 1;
    public static final int DOCUMENT_FIELD_NUMBER = 1;
    private java.util.List<JpPoolDocument> document_;
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    public java.util.List<JpPoolDocument> getDocumentList() {
      return document_;
    }
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    public java.util.List<? extends JpPoolDocumentOrBuilder>
        getDocumentOrBuilderList() {
      return document_;
    }
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    public int getDocumentCount() {
      return document_.size();
    }
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    public JpPoolDocument getDocument(int index) {
      return document_.get(index);
    }
    /**
     * <code>repeated .JpPoolDocument document = 1;</code>
     */
    public JpPoolDocumentOrBuilder getDocumentOrBuilder(
        int index) {
      return document_.get(index);
    }

    private void initFields() {
      document_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < document_.size(); i++) {
        output.writeMessage(1, document_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < document_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, document_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JpPoolProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JpPoolProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JpPoolProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JpPoolProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JpPoolProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JpPoolProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JpPoolProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JpPoolProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JpPoolProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JpPoolProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JpPoolProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JpPoolProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements JpPoolProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JpPoolProbuf.internal_static_JpPoolProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JpPoolProbuf.internal_static_JpPoolProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JpPoolProto.class, Builder.class);
      }

      // Construct using com.ifeng.recom.mixrecall.common.model.JpPoolProbuf.JpPoolProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDocumentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (documentBuilder_ == null) {
          document_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          documentBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JpPoolProbuf.internal_static_JpPoolProto_descriptor;
      }

      public JpPoolProto getDefaultInstanceForType() {
        return JpPoolProto.getDefaultInstance();
      }

      public JpPoolProto build() {
        JpPoolProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public JpPoolProto buildPartial() {
        JpPoolProto result = new JpPoolProto(this);
        int from_bitField0_ = bitField0_;
        if (documentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            document_ = java.util.Collections.unmodifiableList(document_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.document_ = document_;
        } else {
          result.document_ = documentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JpPoolProto) {
          return mergeFrom((JpPoolProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JpPoolProto other) {
        if (other == JpPoolProto.getDefaultInstance()) return this;
        if (documentBuilder_ == null) {
          if (!other.document_.isEmpty()) {
            if (document_.isEmpty()) {
              document_ = other.document_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocumentIsMutable();
              document_.addAll(other.document_);
            }
            onChanged();
          }
        } else {
          if (!other.document_.isEmpty()) {
            if (documentBuilder_.isEmpty()) {
              documentBuilder_.dispose();
              documentBuilder_ = null;
              document_ = other.document_;
              bitField0_ = (bitField0_ & ~0x00000001);
              documentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDocumentFieldBuilder() : null;
            } else {
              documentBuilder_.addAllMessages(other.document_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JpPoolProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JpPoolProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .JpPoolDocument document = 1;
      private java.util.List<JpPoolDocument> document_ =
        java.util.Collections.emptyList();
      private void ensureDocumentIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          document_ = new java.util.ArrayList<JpPoolDocument>(document_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          JpPoolDocument, JpPoolDocument.Builder, JpPoolDocumentOrBuilder> documentBuilder_;

      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public java.util.List<JpPoolDocument> getDocumentList() {
        if (documentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(document_);
        } else {
          return documentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public int getDocumentCount() {
        if (documentBuilder_ == null) {
          return document_.size();
        } else {
          return documentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public JpPoolDocument getDocument(int index) {
        if (documentBuilder_ == null) {
          return document_.get(index);
        } else {
          return documentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder setDocument(
          int index, JpPoolDocument value) {
        if (documentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIsMutable();
          document_.set(index, value);
          onChanged();
        } else {
          documentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder setDocument(
          int index, JpPoolDocument.Builder builderForValue) {
        if (documentBuilder_ == null) {
          ensureDocumentIsMutable();
          document_.set(index, builderForValue.build());
          onChanged();
        } else {
          documentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder addDocument(JpPoolDocument value) {
        if (documentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIsMutable();
          document_.add(value);
          onChanged();
        } else {
          documentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder addDocument(
          int index, JpPoolDocument value) {
        if (documentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIsMutable();
          document_.add(index, value);
          onChanged();
        } else {
          documentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder addDocument(
          JpPoolDocument.Builder builderForValue) {
        if (documentBuilder_ == null) {
          ensureDocumentIsMutable();
          document_.add(builderForValue.build());
          onChanged();
        } else {
          documentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder addDocument(
          int index, JpPoolDocument.Builder builderForValue) {
        if (documentBuilder_ == null) {
          ensureDocumentIsMutable();
          document_.add(index, builderForValue.build());
          onChanged();
        } else {
          documentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder addAllDocument(
          Iterable<? extends JpPoolDocument> values) {
        if (documentBuilder_ == null) {
          ensureDocumentIsMutable();
          super.addAll(values, document_);
          onChanged();
        } else {
          documentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder clearDocument() {
        if (documentBuilder_ == null) {
          document_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          documentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public Builder removeDocument(int index) {
        if (documentBuilder_ == null) {
          ensureDocumentIsMutable();
          document_.remove(index);
          onChanged();
        } else {
          documentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public JpPoolDocument.Builder getDocumentBuilder(
          int index) {
        return getDocumentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public JpPoolDocumentOrBuilder getDocumentOrBuilder(
          int index) {
        if (documentBuilder_ == null) {
          return document_.get(index);  } else {
          return documentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public java.util.List<? extends JpPoolDocumentOrBuilder>
           getDocumentOrBuilderList() {
        if (documentBuilder_ != null) {
          return documentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(document_);
        }
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public JpPoolDocument.Builder addDocumentBuilder() {
        return getDocumentFieldBuilder().addBuilder(
            JpPoolDocument.getDefaultInstance());
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public JpPoolDocument.Builder addDocumentBuilder(
          int index) {
        return getDocumentFieldBuilder().addBuilder(
            index, JpPoolDocument.getDefaultInstance());
      }
      /**
       * <code>repeated .JpPoolDocument document = 1;</code>
       */
      public java.util.List<JpPoolDocument.Builder>
           getDocumentBuilderList() {
        return getDocumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          JpPoolDocument, JpPoolDocument.Builder, JpPoolDocumentOrBuilder>
          getDocumentFieldBuilder() {
        if (documentBuilder_ == null) {
          documentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              JpPoolDocument, JpPoolDocument.Builder, JpPoolDocumentOrBuilder>(
                  document_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          document_ = null;
        }
        return documentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:JpPoolProto)
    }

    static {
      defaultInstance = new JpPoolProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:JpPoolProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JpPoolDocument_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JpPoolDocument_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JpPoolProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JpPoolProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021jpPoolProto.proto\"\327\001\n\016JpPoolDocument\022\030" +
      "\n\020readableFeatures\030\001 \001(\t\022\r\n\005simId\030\002 \001(\t\022" +
      "\r\n\005docid\030\003 \001(\t\022\014\n\004date\030\004 \001(\t\022\r\n\005title\030\005 " +
      "\001(\t\022\020\n\010hotBoost\030\006 \001(\t\022\023\n\013hasThumnail\030\007 \001" +
      "(\010\022\017\n\007docType\030\010 \001(\t\022\016\n\006source\030\t \001(\t\022\r\n\005c" +
      "otag\030\n \001(\t\022\014\n\004isJp\030\013 \001(\010\022\013\n\003why\030\014 \001(\t\"0\n" +
      "\013JpPoolProto\022!\n\010document\030\001 \003(\0132\017.JpPoolD" +
      "ocumentB6\n&com.ifeng.recom.mixrecall.com" +
      "mon.modelB\014JpPoolProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_JpPoolDocument_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_JpPoolDocument_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JpPoolDocument_descriptor,
              new String[] { "ReadableFeatures", "SimId", "Docid", "Date", "Title", "HotBoost", "HasThumnail", "DocType", "Source", "Cotag", "IsJp", "Why", });
          internal_static_JpPoolProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_JpPoolProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JpPoolProto_descriptor,
              new String[] { "Document", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
